lane :post_duration do
  start_time = Time.now

  sleep(3)

  result = mackerel_post_duration(
    api_key: ENV['MACKEREL_API_KEY'],
    service_name: ENV['MACKEREL_SERVICE_NAME'],
    metric_name: "duration.#{ENV['FASTLANE_LANE_NAME']}",
    start_time: start_time
  )
  UI.message(result)
end

lane :post_xcresult do
  scan(
    project: 'examples/SampleApp/SampleApp.xcodeproj',
    scheme: 'SampleApp',
    derived_data_path: 'examples/SampleApp/build',
    output_directory: 'examples/SampleApp/fastlane/test_output'
  )

  file = Dir["#{ENV['PWD']}/SampleApp/build/**/Logs/Test/*.xcresult"].last
  UI.message(file)

  result = mackerel_post_xcresult(
    api_key: ENV['MACKEREL_API_KEY'],
    service_name: ENV['MACKEREL_SERVICE_NAME'],
    metric_name_prefix: 'xcresult',
    file: file
  )
  UI.message(result)
end
